name: Check Format

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  verusfmt:
    name: Check Verus Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Get Verus FMT
        run: cargo install verusfmt
      - name: Verify Node Replication
        run: |
          cd verified-node-replication/src
          for f in ./*.rs; do verusfmt --check $f; done
          for f in ./exec/*.rs; do verusfmt --check $f; done
          for f in ./spec/*.rs; do verusfmt --check $f; done
